# Generated by Django 4.2.11 on 2025-07-12 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='guild',
        ),
    ]
